/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2023-01-03 18:40:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import be.veltri.ENUMS.EnumStatusList;
import java.util.ArrayList;
import be.veltri.JAVABEANS.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("be.veltri.JAVABEANS");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("be.veltri.ENUMS.EnumStatusList");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gift List Home</title>\r\n");
      out.write("</head>\r\n");

User user = (User) session.getAttribute("user");
ArrayList<GiftList> myLists = user.getMyLists();
ArrayList<GiftList> giftLists = user.getLstGiftList();

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".folder {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 105px;\r\n");
      out.write("	margin-right: 40px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-bottom: 50px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	background-color: #bfc3c7;\r\n");
      out.write("	border-radius: 0 6px 6px 6px;\r\n");
      out.write("	box-shadow: 4px 4px 7px rgba(0, 0, 0, 0.59);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".folder:before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: 12px;\r\n");
      out.write("	border-radius: 0 20px 0 0;\r\n");
      out.write("	background-color: #bfc3c7;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: -12px;\r\n");
      out.write("	left: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Home</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<h2><u>Active lists</u></h2>\r\n");
      out.write("		");

		for (GiftList gl : myLists) {
			if (gl.getStatusList().toString().equals(EnumStatusList.Active.toString())){
			
		
      out.write("<button class=\"folder\" onclick=\"location.href='/Veltri_GiftList/getInfoList?orderId=");
      out.print( gl.getIdGiftList() );
      out.write("'\">\r\n");
      out.write("			<p style=\"color: red; margin: 5px;\">My list</p>");
      out.print(gl.getNameList());
      out.write("\r\n");
      out.write("		  </button>\r\n");
      out.write("		");

		}}
		
      out.write("\r\n");
      out.write("		");

		for (GiftList gl : giftLists) {
			if (gl.getStatusList().toString().equals(EnumStatusList.Active.toString())){
		
      out.write("<button class=\"folder\" onclick=\"location.href='/Veltri_GiftList/getInfoList?orderId=");
      out.print( gl.getIdGiftList() );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(gl.getNameList());
      out.write("</button>\r\n");
      out.write("		");

		}}
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<h2><u>Inactive or close lists</u></h2>\r\n");
      out.write("	\r\n");
      out.write("		");

		for (GiftList gl : myLists) {
			if (!gl.getStatusList().toString().equals(EnumStatusList.Active.toString())){
			
		
      out.write("<button class=\"folder\" onclick=\"location.href='/Veltri_GiftList/getInfoList?orderId=");
      out.print( gl.getIdGiftList() );
      out.write("'\">\r\n");
      out.write("			<p style=\"color: red; margin: 5px;\">My list</p>");
      out.print(gl.getNameList());
      out.write("\r\n");
      out.write("		  </button>\r\n");
      out.write("		");

		}}
		
      out.write("\r\n");
      out.write("		");

		for (GiftList gl : giftLists) {
			if (!gl.getStatusList().toString().equals(EnumStatusList.Active.toString())){
		
      out.write("<button class=\"folder\" onclick=\"noAccess()\">");
      out.print(gl.getNameList());
      out.write("</button>\r\n");
      out.write("		");

		}}
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function noAccess(){\r\n");
      out.write("		alert(\"You can't access to inactive or close list\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
