/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2022-12-31 14:32:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import be.veltri.JAVABEANS.*;
import be.veltri.ENUMS.*;
import java.util.*;

public final class ModifyGift_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("be.veltri.JAVABEANS");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("be.veltri.ENUMS");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Modify a gift</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".child {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formType {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write('\r');
      out.write('\n');

ArrayList<String> errors = (ArrayList<String>)request.getAttribute("errorsModifyGift");
Gift gift = (Gift) request.getAttribute("modifyGift");
String where = (String) request.getAttribute("where");
String idGift = (String) request.getAttribute("idGift");
String priorityH = "";
String priorityM = "";
String priorityL = "";
if (gift.getPriority().toString().equals("High"))
	priorityH = "checked";
else if (gift.getPriority().toString().equals("Medium"))
	priorityM = "checked";
else if (gift.getPriority().toString().equals("Low"))
	priorityL = "checked";

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Modify gift</h1>\r\n");
      out.write("	<form action=\"verifModifyGift\" method=\"POST\"\r\n");
      out.write("		enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("		<input type=\"text\" name=\"where\" id=\"formType\" value=\"");
      out.print(where);
      out.write("\" />\r\n");
      out.write("		<input type=\"text\" name=\"idGiftModify\" id=\"formType\" value=\"");
      out.print(idGift);
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"child\">\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<b>Name of the gift :</b> <input type=\"text\" name=\"nameGift\"\r\n");
      out.write("					id=\"nameGift\" value=\"");
      out.print(gift.getName());
      out.write("\" required />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<b>Average price :</b> <input type=\"number\" name=\"price\" id=\"price\"\r\n");
      out.write("					min=\"0\" step=\"1\" value=\"");
      out.print(gift.getAveragePrice());
      out.write("\" required /> €\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"child\">\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("				<b>Description of the gift :</b>\r\n");
      out.write("				<textarea name=\"descGift\" id=\"descGift\" rows=\"4\" cols=\"50\" required>");
      out.print(gift.getDescription());
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"form\">\r\n");
      out.write("			<b>Priority : </b> <input type=\"radio\" name=\"priority\" id=\"high\"\r\n");
      out.write("				value=\"");
      out.print(EnumPriority.High);
      out.write('"');
      out.write(' ');
      out.print(priorityH);
      out.write(" />\r\n");
      out.write("			");
      out.print(EnumPriority.High);
      out.write("\r\n");
      out.write("			<input type=\"radio\" name=\"priority\" id=\"medium\"\r\n");
      out.write("				value=\"");
      out.print(EnumPriority.Medium);
      out.write('"');
      out.write(' ');
      out.print(priorityM);
      out.write(" />\r\n");
      out.write("			");
      out.print(EnumPriority.Medium);
      out.write("\r\n");
      out.write("			<input type=\"radio\" name=\"priority\" id=\"low\"\r\n");
      out.write("				value=\"");
      out.print(EnumPriority.Low);
      out.write('"');
      out.write(' ');
      out.print(priorityL);
      out.write(" />\r\n");
      out.write("			");
      out.print(EnumPriority.Low);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"form\">\r\n");
      out.write("			<b>Web link [optional]: </b><input type=\"text\" name=\"weblink\"\r\n");
      out.write("				id=\"weblink\" value=\"");
      out.print(gift.getWebsiteLink());
      out.write("\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<b>Insert an image [optional]:</b> <input type=\"file\" name=\"image\"\r\n");
      out.write("				id=\"image\" accept=\".jpg, .jpeg, .png\" value=\"blabla\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		<p class=\"form\">\r\n");
      out.write("			<em>Accept only .jpg, .jpeg and .png</em>\r\n");
      out.write("		</p>\r\n");
      out.write("		<button type=\"submit\" name=\"addGiftBtn\" id=\"addGiftBtn\"\r\n");
      out.write("			style=\"margin-top: 30px;\">UPDATE</button>\r\n");
      out.write("			<ul>\r\n");
      out.write("			");

				if (errors != null){
					for (String err : errors){
						
      out.write("\r\n");
      out.write("							<li style=\"color:red;\">");
      out.print(err);
      out.write(" </li>\r\n");
      out.write("						");

					}
				}
				
			
      out.write("</ul>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
